apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: ls2-jan212026
  janus-idp.io/tekton: ls2-jan212026
  backstage.io/kubernetes-id: ls2-jan212026
  backstage.io/kubernetes-namespace: hello2
  app.kubernetes.io/part-of: ls2-jan212026
resources:
  - application-dev.yaml
