apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ls2-jan212026
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: streamlit-app
          image: quay.io/maysunfaisal/ls2-jan212026:6c6cbf31aa9f09f1c042d41cd088eb401cf31edf@sha256:5a0d152ffefc716123de9595260929a219688278afc6a32c62248a3715ab06c6
